runtime: python39
service: default
instance_class: F1

handlers:
  - url: /
    static_files: src/views/login.html
    upload: src/views/login.html

  - url: /(.*)
    static_files: src/views/\1
    upload: src/views/(.*)

  - url: /assets
    static_dir: src/assets

default_expiration: "1h"
