runtime: python39
service: default
instance_class: F1

handlers:
  # Route default ke login.html
  - url: /
    static_files: src/views/login.html
    upload: src/views/login.html

  # Untuk semua file HTML (books.html, register.html, dll)
  - url: /(.*\.html)
    static_files: src/views/\1
    upload: src/views/(.*\.html)

default_expiration: "1h"
